name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tests
      run: |
        python -m pytest tests/

    - name: 'Google Auth'
      id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    # First submit the build and capture the build ID
    - name: 'Submit build'
      id: build
      run: |
        gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-app 2>&1 | tee build.log
        BUILD_ID=$(grep 'Created \[' build.log | sed 's/.*\[\(.*\)\].*/\1/')
        echo "build_id=$BUILD_ID" >> $GITHUB_OUTPUT

    # Then stream the logs
    - name: 'Stream build logs'
      if: steps.build.outputs.build_id != ''
      run: |
        gcloud builds log --stream ${{ steps.build.outputs.build_id }}

    - name: 'Deploy to Cloud Run'
      uses: 'google-github-actions/deploy-cloudrun@v1'
      with:
        service: 'my-app'
        region: 'us-central1'
        image: 'gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-app'
        flags: '--allow-unauthenticated'